### ISSUE TITLE
Fullscreen not working in Linux

### ISSUE THREAD

**Issue by hexpunk** [ekunuke/vagante_issues#159]
Similar to the now-closed https://github.com/ekunuke/vagante_issues/issues/57, I find that fullscreen doesn't work on Linux.  I'm running the latest version of Vagante from Steam on Ubuntu 16.04.  When I change the setting to turn on fullscreen in the game, the title bar of the window still appears.  If I restart the game with the fullscreen option already turned on, the game still appears as a window, but unlike with fullscreen turned off, there's no way to resize the window or maximize it.

**Comment by hexpunk** [comment]
My window manager/desktop environment is Unity 7.4.5+16.04.20180221, which is the latest version available.

**Comment by BlackCapCoder** [comment]
Sorry, I deleted my comment when I re-read your message and saw Ubuntu.

Personally I really appreciate how vagante handles "fullscreen". On something like windows, games commonly change the screen resolution and lock you in to the game so that there is no easy way to quickly check a web browser or change song or whatever.

I don't need my games to do window management for me. To me "fullscreen-mode" means "hey, I want you to render at this very specific resolution please", and whether that window actually covers the entirety  of the screen should be up to me and my window manager.
